### ISSUE TITLE
Changing a adbd path.

### ISSUE THREAD

**Issue by barami** [nadlabak/android_device_motorola_umts_sholes#2]
Hi.

After flashing cm7.1 for motorola, i can't connect phont by adb.
Because, adbd position is moved /system/etc/rootfs/sbin.
After booted phone, /sbin was empty.

But, init.rc script has a don't changed, and can't run adbd service.

It need to be change path in init.rc or mount(or symbolic link) rootfs/sbin to /sbin.

**Comment by lempere** [comment]
I have the same issue. And is important to debug my applications.

**Comment by barami** [comment]
I found a reason. It's permission problem. I see a adbd in sbin by root explorer. OI file viewer cannot see files in sbin. :(
After flashing, /system/etc/rootfs/sbin/adbd has a permission 644.
It is not executable. So, I changed permission to 750 and successfully connect to my phone.

It need to be fix a updater-script.

**Comment by lempere** [comment]
I put the mobile in recovery mode
Then I can access to android shell chmod 750  /system/etc/rootfs/sbin/adbd  .
And when I reboot the phone works!! 

Now I can connect to the pc. 

Thanks

**Comment by nadlabak** [comment]
/system/etc/rootfs/sbin/adbd is copied to /sbin/adbd and its permissions are set by the sh_hijack script:
https://github.com/nadlabak/android_device_motorola_umts_sholes/blob/gingerbread/prebuilt/bin/sh_hijack.sh#L8
